name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
      SIGNING_KEY: ${{ secrets.P_KEY_ARMORED }}
      SIGNING_PASSWORD: ${{ secrets.P_KEY_PASSPHRASE }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Deploy
        run: ./gradlew publishAllPublicationsToSonatypeRepository closeAndReleaseSonatypeStagingRepository